apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nocode.fullname" . }}
  labels:
    {{- include "nocode.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nocode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
      {{- end }}
        timestamp: "{{ now | date "20060102150405" }}"
      labels:
        {{- include "nocode.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ include "nocode.dockerSecretName" . }}
      serviceAccountName: {{ include "nocode.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "nocode.envSecretName" . }}
          ports:
            - name: http-proxy
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.healthPath }}
              port: {{ .Values.deployment.containerPort }}
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.healthPath }}
              port: {{ .Values.deployment.containerPort }}
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if (.Files.Glob "files/*.opz") }}
          volumeMounts:
            - name: custom-config
              mountPath: /data
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if (.Files.Glob "files/*.opz")  }}
      volumes:
        - name: custom-config
          configMap:
            name: {{ include "nocode.fullname" . }}-config
      {{- end }}
