{{- if .Values.imageCredentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nocode.dockerSecretName" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}
